[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fracfeedextractor"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pymupdf",
    "pillow",
    "pytesseract",
    "scikit-learn",
    "python-dotenv",
    "google-auth",
    "google-auth-oauthlib",
    "google-auth-httplib2",
    "numpy",
    "google-api-python-client",
    "ollama",
    "anthropic",
    "pydantic",
    "camelot-py[base]",
    "opencv-python",
    "pymupdf_layout",
    "xgboost",
    "pyspellchecker",
    "joblib",
    "requests",
    "diskcache",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "coverage",
    "flake8==6.1.0",
    "black==25.9.0",
]

[tool.black]
line-length = 200
target-version = ["py311"]
skip-string-normalization = true
exclude = '''
/(
    \.git
  | __pycache__
  | build
  | dist
  | venv
  | \.venv
  | \.mypy_cache
  | htmlcov
)/
'''

[tool.pytest.ini_options]
addopts = "-ra --disable-warnings"
testpaths = [
    "tests"
]
filterwarnings = [
    "ignore::DeprecationWarning"
]

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["tests/*"]

[tool.coverage.report]
show_missing = true
skip_covered = true
precision = 1
